import {defineField, defineType} from 'sanity'

export const application = defineType({
  name: 'application',
  title: 'Application',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'links', title: 'Internal Links'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'imageWithAlt',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'portableText',
      group: 'content',
    }),
    defineField({
      name: 'painPoints',
      title: 'Pain Points',
      type: 'array',
      group: 'content',
      of: [{type: 'featureItem'}],
    }),
    defineField({
      name: 'solutionBenefits',
      title: 'Solution Benefits',
      type: 'array',
      group: 'content',
      of: [{type: 'featureItem'}],
    }),
    defineField({
      name: 'installationScenarios',
      title: 'Installation Scenarios',
      type: 'array',
      group: 'content',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'recommendedProducts',
      title: 'Recommended Products',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'relatedCaseStudies',
      title: 'Related Shows & Events',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'caseStudy'}]}],
    }),
    defineField({
      name: 'relatedFaqs',
      title: 'Related FAQs',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'faq'}]}],
    }),
    defineField({
      name: 'cta',
      title: 'CTA',
      type: 'cta',
      group: 'links',
    }),
    defineField({
      name: 'relatedBlogs',
      title: 'Related Blogs',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'blogPost'}]}],
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: {title: 'title', subtitle: 'slug.current', media: 'heroImage.image'},
  },
})
