import {defineField, defineType} from 'sanity'

export const caseStudy = defineType({
  name: 'caseStudy',
  title: 'Shows & Events',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'links', title: 'Internal Links'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'projectType',
      title: 'Project Type',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'clientType',
      title: 'Client Type',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'industry',
      title: 'Industry',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'projectYear',
      title: 'Project Year',
      type: 'number',
      group: 'content',
    }),
    defineField({
      name: 'eventStartDate',
      title: 'Event start date',
      type: 'date',
      group: 'content',
      description: 'Shown on Shows & Events listing (e.g. trade fair dates).',
    }),
    defineField({
      name: 'eventEndDate',
      title: 'Event end date',
      type: 'date',
      group: 'content',
    }),
    defineField({
      name: 'venue',
      title: 'Venue / city (display)',
      type: 'string',
      group: 'content',
      description: 'e.g. Guangzhou China',
    }),
    defineField({
      name: 'boothNumber',
      title: 'Booth number',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'showWebsiteUrl',
      title: 'Official show website URL',
      type: 'url',
      group: 'content',
    }),
    defineField({
      name: 'appointmentUrl',
      title: 'Appointment / contact link',
      type: 'string',
      group: 'content',
      description: 'Defaults to /contact. Use full URL or site path.',
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 3,
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'imageWithAlt',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'portableText',
      group: 'content',
    }),
    defineField({
      name: 'clientBackground',
      title: 'Client Background',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'challenge',
      title: 'Challenge',
      type: 'portableText',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'solution',
      title: 'Solution',
      type: 'portableText',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'productsUsed',
      title: 'Products Used',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'result',
      title: 'Result',
      type: 'array',
      group: 'content',
      of: [
        {
          type: 'object',
          fields: [
            {name: 'metric', title: 'Metric', type: 'string'},
            {name: 'description', title: 'Description', type: 'string'},
          ],
        },
      ],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'clientFeedback',
      title: 'Client Feedback',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'content',
      of: [{type: 'imageWithAlt'}],
    }),
    defineField({
      name: 'usedProducts',
      title: 'Used Products',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'relatedApplications',
      title: 'Related Applications',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'application'}]}],
    }),
    defineField({
      name: 'similarCaseStudies',
      title: 'Similar Shows & Events',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'caseStudy'}]}],
    }),
    defineField({
      name: 'inquiryCtaText',
      title: 'Inquiry CTA Text',
      type: 'string',
      group: 'links',
      initialValue: 'Request a Quote',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'relatedProducts',
      title: 'Related Products',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'cta',
      title: 'CTA',
      type: 'cta',
      group: 'links',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: {title: 'title', subtitle: 'country', media: 'heroImage.image'},
  },
})
