import {defineField, defineType} from 'sanity'

export const product = defineType({
  name: 'product',
  title: 'Product',
  type: 'document',
  groups: [
    {name: 'basic', title: 'Basic Info', default: true},
    {name: 'media', title: 'Media'},
    {name: 'specs', title: 'Specs'},
    {name: 'business', title: 'Business'},
    {name: 'tabs', title: 'Detail Tabs'},
    {name: 'links', title: 'Internal Links'},
    {name: 'seo', title: 'SEO Settings'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Product Name',
      type: 'string',
      group: 'basic',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'basic',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{type: 'productCategory'}],
      group: 'basic',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'price',
      title: 'Price (USD)',
      type: 'number',
      group: 'basic',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      group: 'basic',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'imageWithAlt',
      group: 'media',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'mainImage',
      title: 'Main Image',
      type: 'image',
      group: 'media',
      options: {hotspot: true},
      fields: [
        defineField({
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
        }),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery (Images under main image)',
      type: 'array',
      group: 'media',
      description: 'Upload additional images to show under the main image. Order matters.',
      of: [
        {
          type: 'image',
          options: {hotspot: true},
          fields: [
            defineField({
              name: 'alt',
              title: 'Alt Text',
              type: 'string',
            }),
          ],
        },
      ],
    }),
    defineField({
      name: 'specifications',
      title: 'Advanced Parameters',
      type: 'array',
      group: 'specs',
      of: [{type: 'specification'}],
    }),
    defineField({
      name: 'keyFeatures',
      title: 'Key Features',
      type: 'array',
      group: 'specs',
      of: [{type: 'featureItem'}],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'technicalSpecifications',
      title: 'Technical Specifications',
      type: 'array',
      group: 'specs',
      of: [{type: 'specification'}],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'applications',
      title: 'Applications',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'application'}]}],
    }),
    defineField({
      name: 'customizationOptions',
      title: 'Customization Options',
      type: 'array',
      group: 'business',
      of: [{type: 'string'}],
    }),
    defineField({
      name: 'moq',
      title: 'MOQ',
      type: 'string',
      group: 'business',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'leadTime',
      title: 'Lead Time',
      type: 'string',
      group: 'business',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'sampleAvailable',
      title: 'Sample Available',
      type: 'boolean',
      group: 'business',
      initialValue: false,
    }),
    defineField({
      name: 'certifications',
      title: 'Certifications',
      type: 'array',
      group: 'business',
      of: [{type: 'reference', to: [{type: 'certification'}]}],
    }),
    defineField({
      name: 'description',
      title: 'Overview (Portable Text)',
      type: 'array',
      group: 'tabs',
      of: [{type: 'block'}],
    }),
    defineField({
      name: 'detailTabs',
      title: 'Multi-tab Content',
      type: 'array',
      group: 'tabs',
      of: [{type: 'productDetailTab'}],
      description: 'For spec tab, installation tab, packaging tab, etc.',
    }),
    defineField({
      name: 'relatedApplications',
      title: 'Related Applications',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'application'}]}],
    }),
    defineField({
      name: 'relatedCaseStudies',
      title: 'Related Shows & Events',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'caseStudy'}]}],
    }),
    defineField({
      name: 'relatedFaqs',
      title: 'Related FAQs',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'faq'}]}],
    }),
    defineField({
      name: 'cta',
      title: 'CTA',
      type: 'cta',
      group: 'links',
    }),
    defineField({
      name: 'relatedProducts',
      title: 'Related Products',
      type: 'array',
      group: 'links',
      of: [{type: 'reference', to: [{type: 'product'}]}],
    }),
    defineField({
      name: 'seo',
      title: 'SEO Configuration',
      type: 'seo',
      group: 'seo',
      validation: (rule) => rule.required(),
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'category.title',
      media: 'mainImage',
    },
  },
})
